# Data
path: C:\Users\jeuch\Documents\GitHub\traffic-watch\data\cars
train: images/train 
val: images/val

# Keypoints
kpt_shape: [16, 3]  # [number of keypoints, number of dim]
flip_idx: [2, 1, 0, 5, 6, 3, 4, 9, 10, 7, 8, 13, 12, 11, 15, 14]

# Classes
names:
  0: car